version: 1
disable_existing_loggers: false
formatters:
  console:
    format: "### %(name)s - %(message)s ###"
  logfile:
    format: "### %(asctime)s - %(name)s - %(message)s ###"
  debug:
    format: "### %(asctime)s - %(name)s - %(message)s ###"
filters:
  exclude_warnings:
    "()": wavealign.utility.logging.exclude_warnings_filter.ExcludeWarningsFilter
handlers:
  info:
    class: wavealign.utility.logging.tqdm_console_handler.TqdmConsoleHandler
    level: INFO
    formatter: console
    filters: []
  warning:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: logfile
    filename: log_file_path
    maxBytes: 5000000
    backupCount: 3
    delay: true
  warning_count:
    class: wavealign.utility.logging.warning_handler.WarningHandler
    level: WARNING
  debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: debug
    filename: log_file_path
    filters:
      - exclude_warnings
loggers:
  root:
    level: log_level
    handlers:
      - info
      - warning
      - warning_count
      - debug
  ffmpegio:
    propagate: false
